version: '3.4'

services:
  silo:
    image: ${DOCKER_REGISTRY-}silo
    build:
      context: .
      dockerfile: Silo/Dockerfile
    volumes:
    - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  client:
    image: ${DOCKER_REGISTRY-}client
    depends_on:
    - silo
    build:
      context: .
      dockerfile: Client/Dockerfile
    volumes:
    - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

