version: '3.4'

services:
  silo:
    image: ${DOCKER_REGISTRY-}silo
    build:
      context: .
      dockerfile: Silo/Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client/Dockerfile

